//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalancePaymentSupport
    {
        public int idBalance { get; set; }
        public int id { get; set; }
        public byte[] soporte { get; set; }
    
        public virtual Balance Balance { get; set; }
    }
}
