//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDetail
    {
        public int idBalance { get; set; }
        public int idApartamento { get; set; }
        public int idConcepto { get; set; }
        public string tipo { get; set; }
        public decimal valor { get; set; }
    
        public virtual Balance Balance { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual ProjectDistribution ProjectDistribution { get; set; }
    }
}
