//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPaymentSupport
    {
        public int id { get; set; }
        public int idFactura { get; set; }
        public Nullable<int> idTipoPago { get; set; }
        public string soporte { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fechaPago { get; set; }
        public Nullable<bool> aceptado { get; set; }
        public string observaciones { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual PropertyBill PropertyBill { get; set; }
    }
}
