//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int id { get; set; }
        public int idPropiedad { get; set; }
        public Nullable<int> idFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idConcepto { get; set; }
        public decimal valor { get; set; }
        public bool pagado { get; set; }
    
        public virtual Concept Concept { get; set; }
        public virtual ProjectDistribution ProjectDistribution { get; set; }
        public virtual PropertyBill PropertyBill { get; set; }
    }
}
