//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept
    {
        public Concept()
        {
            this.BalanceDetail = new HashSet<BalanceDetail>();
        }
    
        public int id { get; set; }
        public int idProyecto { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<BalanceDetail> BalanceDetail { get; set; }
        public virtual Project Project { get; set; }
    }
}
