//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDistribution
    {
        public ProjectDistribution()
        {
            this.Charge = new HashSet<Charge>();
        }
    
        public int idProyecto { get; set; }
        public int id { get; set; }
        public Nullable<System.Guid> idPadre { get; set; }
        public string descripcion { get; set; }
        public bool edificio { get; set; }
        public bool propiedad { get; set; }
        public bool areaComun { get; set; }
        public bool alquilable { get; set; }
        public Nullable<int> idConcepto { get; set; }
        public Nullable<int> idPropietario { get; set; }
        public Nullable<int> idTitular { get; set; }
        public bool titularPagaAdministracion { get; set; }
        public bool mora { get; set; }
        public Nullable<System.DateTime> inicioMora { get; set; }
        public bool sancion { get; set; }
        public Nullable<System.DateTime> inicioSancion { get; set; }
    
        public virtual ICollection<Charge> Charge { get; set; }
        public virtual People People { get; set; }
        public virtual People People1 { get; set; }
        public virtual Project Project { get; set; }
    }
}
