//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.BillGeneration = new HashSet<BillGeneration>();
            this.Concept = new HashSet<Concept>();
            this.ProjectDistribution = new HashSet<ProjectDistribution>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string razonSocial { get; set; }
        public string direccion { get; set; }
        public string nit { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string url { get; set; }
        public string logo { get; set; }
        public Nullable<int> idAdministrador { get; set; }
        public string periodoPago { get; set; }
        public int diaInicialPeriodo { get; set; }
        public int diaFinalPeriodo { get; set; }
        public int diaCorteLiquidacion { get; set; }
        public int diasPrimeraFechaPago { get; set; }
        public Nullable<int> diasSeguntaFechaPago { get; set; }
        public decimal porcentajeMora { get; set; }
    
        public virtual ICollection<BillGeneration> BillGeneration { get; set; }
        public virtual ICollection<Concept> Concept { get; set; }
        public virtual People People { get; set; }
        public virtual ICollection<ProjectDistribution> ProjectDistribution { get; set; }
    }
}
