//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Porthos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDistribution
    {
        public ProjectDistribution()
        {
            this.BalanceDetail = new HashSet<BalanceDetail>();
        }
    
        public int idProyecto { get; set; }
        public int id { get; set; }
        public Nullable<System.Guid> idPadre { get; set; }
        public string descripcion { get; set; }
        public bool edificio { get; set; }
        public bool apartamento { get; set; }
        public Nullable<int> idPropietario { get; set; }
        public Nullable<int> idTitular { get; set; }
        public Nullable<bool> mora { get; set; }
    
        public virtual ICollection<BalanceDetail> BalanceDetail { get; set; }
        public virtual People People { get; set; }
        public virtual People People1 { get; set; }
        public virtual Project Project { get; set; }
    }
}
